apiVersion: v1
kind: Service
metadata:
  name: reverse-app
spec:
  selector:
    app: reverse-app
  ports:
    - protocol: TCP
      port: {{ .Values.reverseApp.port }}
      targetPort: {{ .Values.reverseApp.port }}

