apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: {{ .Values.helloworldApp.port }}
      targetPort: {{ .Values.helloworldApp.port }}